// Generated by https://quicktype.io

export interface Student {
    Id:                               number;
    Id_dimension_nacionalidad:        number;
    Id_dimension_nacionalidad_Nombre: string;
    Id_pais_origen:                   number;
    Id_pais_origen_Nombre:            string;
    Id_municipio_origen:              number;
    Id_municipio_origen_Nombre:       string;
    Id_comunidad_origen:              null;
    Id_comunidad_origen_Nombre:       string;
    Id_estado_provincia:              null;
    Id_estado_provincia_Nombre:       string;
    Id_sexo:                          number;
    Id_sexo_Nombre:                   string;
    Id_etnia:                         number;
    Id_etnia_Nombre:                  string;
    Id_tipo_sangre:                   number;
    Id_tipo_sangre_Nombre:            string;
    Id_tipo_identidad:                number;
    Id_tipo_identidad_Nombre:         string;
    Id_zona_procedencia:              number;
    Id_zona_procedencia_Nombre:       string;
    Id_centro_secundaria:             number;
    Id_centro_secundaria_Nombre:      string;
    Id_carrera_tecnica:               null;
    Id_carrera_tecnica_Nombre:        string;
    Id_opcion_clasifico:              number;
    Id_opcion_clasifico_Nombre:       string;
    Nombres:                          string;
    Apellidos1:                       string;
    Apellido2:                        string;
    Codigo_MINED:                     string;
    Carrera_tecnica:                  boolean;
    Numero_identidad:                 string;
    Fecha_nacimiento:                 Date;
    Nota_promedio_ingreso:            number;
    Nota_final_ingreso:               number;
    Anio_ingreso_carrera:             number;
    Fecha_Registro:                   Date;
    Fecha_Modificacion:               Date;
    IdUsuario:                        number;
    IdDominio:                        number;
    Estado:                           number;
}

// Generated by https://quicktype.io

export interface Result<T> {
    message: string;
    data:    T;
}